services:
  # Limpiar base de datos
  Maxtoan\ToolsBundle\Command\DataBaseClearCommand:
      tags:
            - { name: 'console.command', command: 'mtools:database:clear' }
  # Limpiar carpetas
  Maxtoan\ToolsBundle\Command\FolderClearCommand:
      tags:
            - { name: 'console.command', command: 'mtools:folder:clear' }