services:
  # Generador de enlaces
  maxtoan_tools.service.link_generator:
      class: Maxtoan\ToolsBundle\Service\LinkGenerator\LinkGeneratorService
      calls: 
          - [setContainer, ['@service_container']]
  # Extension Twig generador de link
  maxtoan_tools.twig.extension_link:
      class: Maxtoan\ToolsBundle\Twig\Extension\LinkGeneratorExtension
      tags:
          - { name: twig.extension}
      calls:
          - [ setLinkGeneratorService, ['@maxtoan_tools.service.link_generator']]