services:
  # Generador de enlaces
  maximosojo_tools.service.link_generator:
      class: Maximosojo\ToolsBundle\Service\LinkGenerator\LinkGeneratorService
      calls: 
          - [setContainer, ['@service_container']]
  # Extension Twig generador de link
  maximosojo_tools.twig.extension_link:
      class: Maximosojo\ToolsBundle\Twig\Extension\LinkGeneratorExtension
      tags:
          - { name: twig.extension}
      calls:
          - [ setLinkGeneratorService, ['@maximosojo_tools.service.link_generator']]