services:
    maximosojo_tools.symfonymailer.adapter.orm:
        class: Maximosojo\ToolsBundle\Service\Mailer\Adapter\DoctrineORMAdapter
        arguments: ["@maximosojo_tools.repository.mailer.em",{"mailer_template_class": "%maximosojo_tools.symfonymailer.mailer_template_class%", "mailer_component_class": "%maximosojo_tools.symfonymailer.mailer_component_class%" }]
    Maximosojo\ToolsBundle\Service\Mailer\TwigSymfonyMailer:
        public: true
        arguments: ["@mailer","@twig","@maximosojo_tools.symfonymailer.adapter.orm",{ debug_mail: "%debug_mail%", env: "%kernel.environment%",from_email: "%mailer_user%", from_name: "%from_name%",debug: "%kernel.debug%" }]