services:
    maximosojo_tools.notifier.mailer.adapter.orm:
        class: Maximosojo\ToolsBundle\Service\Notifier\Mailer\Adapter\DoctrineORMAdapter
        arguments: ["@maximosojo_tools.repository.mailer.em",{"template_class": "%maximosojo_tools.notifier.mailer.template_class%", "component_class": "%maximosojo_tools.notifier.mailer.component_class%", "queue_class": "%maximosojo_tools.notifier.mailer.queue_class%" }]
    Maximosojo\ToolsBundle\Service\Notifier\MailerManager:
        public: true
        arguments: ["@mailer","@twig","@maximosojo_tools.notifier.mailer.adapter.orm",{ debug_mail: "%debug_mail%", env: "%kernel.environment%",from_email: "%mailer_user%", from_name: "%from_name%",debug: "%kernel.debug%" }]