services:
  # Extension tools para breadcrumb
  maximosojo_tools.core.extension:
      class: Maximosojo\ToolsBundle\Twig\Extension\CoreExtension
      tags:
          - { name: twig.extension}      
      calls: 
          - [setContainer, ['@service_container']]
          
  # Secuence generator
  maximosojo_tools.sequence_generator:
      class: Maximosojo\ToolsBundle\Service\SequenceGenerator\SequenceGeneratorService
      calls: 
          - [setContainer, ['@service_container']]
          
  # Manejador de tabs
  maximosojo_tools.manager.tabs:
      class: Maximosojo\ToolsBundle\Service\Tabs\TabsManager
      arguments: ["@request_stack"]
      calls: 
          - [setContainer, ['@service_container']]

  configuration.adapter.orm:
      class: Maximosojo\ToolsBundle\Service\Core\Configuration\Adapter\DoctrineORMAdapter
      arguments: ["@doctrine.orm.entity_manager", "App\\Entity\\M\\Core\\Configuration"]

  # Manejador de paginador
  maximosojo_tools.twig.extension_paginator:
      class: Maximosojo\ToolsBundle\Twig\Extension\PaginatorExtension
      arguments: ["@twig","@request_stack"]
      tags:
          - { name: twig.extension }