services:
    maxtoan_tools.object_manager.default:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManager
        public: false
        arguments: ["@maxtoan_tools.document_manager","@maxtoan_tools.exporter_manager","@maxtoan_tools.statistics_manager"]
        calls:
            - [ setOptions, ["%maxtoan_tools.object_manager.options%"]  ]
    Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManagerInterface:
        alias: maxtoan_tools.object_manager
        public: false