services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    maxtoan_tools.object_manager.default:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManager
        public: false
        calls:
            - [ setOptions, ["%maxtoan_tools.object_manager.options%"]  ]
            - [ setContainer, ['@service_container']  ]
    Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManagerInterface:
        alias: maxtoan_tools.object_manager
        public: false