services:
    maxtoan_tools.object_manager.default:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManager
        public: false
        calls:
            - [ setOptions, ["%maxtoan_tools.object_manager.options%"]  ]
            - [ setContainer, ['@service_container']  ]
    Maxtoan\ToolsBundle\Service\ObjectManager\ObjectDataManagerInterface:
        alias: maxtoan_tools.object_manager
        public: false