services:
  # Manejador
  maximosojo_tools.service.search_manager:
      class: Maximosojo\ToolsBundle\Service\Core\Search\SearchManager
      calls: 
          - [ setTwig, ['@twig']]
          - [ setContainer, ['@service_container']]
  # Extension Twig
  maximosojo_tools.twig.extension_search:
      class: Maximosojo\ToolsBundle\Twig\Extension\SearchExtension
      tags:
          - { name: twig.extension}
      calls:
          - [ setSearchManager, ['@maximosojo_tools.service.search_manager']]