services:
  # Manejador
  maxtoan_tools.service.search_manager:
      class: Maxtoan\ToolsBundle\Service\Core\Search\SearchManager
      calls: 
          - [ setTwig, ['@twig']]
          - [setContainer, ['@service_container']]
  # Extension Twig
  maxtoan_tools.twig.extension_search:
      class: Maxtoan\ToolsBundle\Twig\Extension\SearchExtension
      tags:
          - { name: twig.extension}
      calls:
          - [ setSearchManager, ['@maxtoan_tools.service.search_manager']]