services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    liform.symfony_constraints_parser:
        class: Maxtoan\ToolsBundle\Component\Liform\SymfonyConstraintsParser
    
    liform.transformer.array:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\CollectionTransformer
        arguments: ["@translator","@liform.guesser.validator","@liform.resolver"]
        tags:
            - { name: liform.transformer, form_type: collection, widget: collection }
    
    liform.transformer.boolean:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\BooleanTransformer
        tags:
            - { name: liform.transformer, form_type: checkbox, widget: checkbox }
    
    liform.transformer.choice:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\ChoiceTransformer
        tags:
            - { name: liform.transformer, form_type: choice, widget: choice }
    
    liform.transformer.string:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\StringTransformer
        tags:
            - { name: liform.transformer, form_type: text, widget: text }
            - { name: liform.transformer, form_type: url, widget: url }
            - { name: liform.transformer, form_type: search, widget: search }
            - { name: liform.transformer, form_type: money, widget: money }
            - { name: liform.transformer, form_type: password, widget: password }
            - { name: liform.transformer, form_type: textarea, widget: textarea }
            - { name: liform.transformer, form_type: time, widget: time }
            - { name: liform.transformer, form_type: percent, widget: percent }
            - { name: liform.transformer, form_type: email, widget: email }
            - { name: liform.transformer, form_type: date, widget: date }
            - { name: liform.transformer, form_type: datetime, widget: datetime }
    
    liform.transformer.compound:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\CompoundTransformer
        arguments: ["@translator","@liform.guesser.validator","@liform.resolver"]
        tags:
            - { name: liform.transformer, form_type: compound}
        calls:
            - [ setConstraintsParsers, ["@liform.symfony_constraints_parser"]  ]
    
    liform.transformer.tetranz_select2entity:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\Select2EntityTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: tetranz_select2entity, widget: select2entity }
    
    liform.transformer.readonly:
        class: Maxtoan\ToolsBundle\Component\Liform\Transformer\ReadOnlyTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: readonly, widget: readonly }