services:
    # Manejador de documentos
    maxtoan_tools.document_manager_disk_adapter:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\DocumentManager\Adapter\DiskAdapter
        arguments:
            - { "debug": "%kernel.debug%", "base_path": "%kernel.root_dir%/../var", "documents_path": "documents","env": "%kernel.environment%" }
    maxtoan_tools.document_manager:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\DocumentManager\DocumentManager
        public: true

    # Manejador de exportables
    maxtoan_tools.exporter_manager_doctrine_orm_adapter:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\ExporterManager\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine.orm.default_entity_manager"]
    maxtoan_tools.exporter_manager:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\ExporterManager\ExporterManager
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]
    
    # Manejador de plantillas     
    Maxtoan\ToolsBundle\Service\ObjectManager\ExporterManager\Engine\PhpSpreadsheetXLSXEngine:
        arguments: []
        public: false
    Maxtoan\ToolsBundle\Service\ObjectManager\ExporterManager\Engine\TCPDFEngine:
        arguments: ["@twig"]
        public: false
    Maxtoan\ToolsBundle\Service\ObjectManager\ExporterManager\TemplateService:
        arguments: [ {"debug":"%kernel.debug%", "env": "%kernel.environment%"} ]
        calls:
            - [ addEngine, ["@Maxtoan\\ToolsBundle\\Service\\ObjectManager\\ExporterManager\\Engine\\TCPDFEngine"]  ]
            - [ addEngine, ["@Maxtoan\\ToolsBundle\\Service\\ObjectManager\\ExporterManager\\Engine\\PhpSpreadsheetXLSXEngine"]  ]