services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    maximosojo_tools.document_manager_disk_adapter:
        class: Maximosojo\ToolsBundle\Service\ObjectManager\DocumentManager\Adapter\DiskAdapter
        arguments:
            - { "debug": "%kernel.debug%", "base_path": "%kernel.project_dir%/var", "documents_path": "documents","env": "%kernel.environment%" }
    
    maximosojo_tools.document_manager.default:
        class: Maximosojo\ToolsBundle\Service\ObjectManager\DocumentManager\DocumentManager
        public: true
        
    Maximosojo\ToolsBundle\Service\ObjectManager\DocumentManager\DocumentManagerInterface:
        alias: maximosojo_tools.document_manager

    Maximosojo\ToolsBundle\Controller\ObjectManager\DocumentManagerController:
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]