services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    maxtoan_tools.document_manager_disk_adapter:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\DocumentManager\Adapter\DiskAdapter
        arguments:
            - { "debug": "%kernel.debug%", "base_path": "%kernel.project_dir%/../var", "documents_path": "documents","env": "%kernel.environment%" }
    
    maxtoan_tools.document_manager.default:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\DocumentManager\DocumentManager
        public: true
        
    Maxtoan\ToolsBundle\Service\ObjectManager\DocumentManager\DocumentManagerInterface:
        alias: maxtoan_tools.document_manager