services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    maximosojo_tools.exporter_manager_doctrine_orm_adapter:
        class: Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine.orm.default_entity_manager"]

    maximosojo_tools.exporter_manager.default:
        class: Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\ExporterManager
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]

    Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\ExporterManagerInterface:
        alias: maximosojo_tools.exporter_manager
    
    # Manejador de plantillas
    Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\Engine\PhpSpreadsheetXLSXEngine:
        arguments: []
    Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\Engine\TCPDFEngine:
        arguments: ["@twig"]
    Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\Engine\TCPDFNativeEngine:
        arguments: []
    
    maximosojo_tools.template_service:
        class: Maximosojo\ToolsBundle\Service\ObjectManager\ExporterManager\TemplateService
        public: true
        arguments: [ {"debug":"%kernel.debug%", "env": "%kernel.environment%"} ]
        calls:
            - [ addEngine, ["@Maximosojo\\ToolsBundle\\Service\\ObjectManager\\ExporterManager\\Engine\\TCPDFEngine"]  ]
            - [ addEngine, ["@Maximosojo\\ToolsBundle\\Service\\ObjectManager\\ExporterManager\\Engine\\TCPDFNativeEngine"]  ]
            - [ addEngine, ["@Maximosojo\\ToolsBundle\\Service\\ObjectManager\\ExporterManager\\Engine\\PhpSpreadsheetXLSXEngine"]  ]

    Maximosojo\ToolsBundle\Controller\ObjectManager\ExporterManagerController:
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]