services:
    maxtoan_tools.statistics_manager:
        class: Maxtoan\ToolsBundle\Service\ObjectManager\StatisticManager\StatisticsManager
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]